### ISSUE TITLE
Comparison with code_aster

### ISSUE THREAD

**Issue by desoza** [kostyfisik/FEA-compare#7]
Hi,

Please find attached a proposal for the comparison with Salome-Meca/code_aster (FEA software for structural mechanics).

Best regards,

Salome-Meca and code_aster development team

[main_keys.txt](https://github.com/kostyfisik/FEA-compare/files/825145/main_keys.txt)

**Comment by kostyfisik** [comment]
Great, thank you! The updated table https://cdn.rawgit.com/kostyfisik/FEA-compare/9470ec7237bf180c258ade11bc22696aa46402f8/table.html
